// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file tickets/v1/events.proto (package tickets.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Ticket } from "./tickets_pb.js";
import { file_tickets_v1_tickets } from "./tickets_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tickets/v1/events.proto.
 */
export const file_tickets_v1_events: GenFile = /*@__PURE__*/
  fileDesc("Chd0aWNrZXRzL3YxL2V2ZW50cy5wcm90bxIKdGlja2V0cy52MSJ2Cg1UaWNrZXRDcmVhdGVkEhAKCGV2ZW50X2lkGAEgASgJEi8KC29jY3VycmVkX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIiCgZ0aWNrZXQYAyABKAsyEi50aWNrZXRzLnYxLlRpY2tldCJ2Cg1UaWNrZXRVcGRhdGVkEhAKCGV2ZW50X2lkGAEgASgJEi8KC29jY3VycmVkX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIiCgZ0aWNrZXQYAyABKAsyEi50aWNrZXRzLnYxLlRpY2tldEI4WjZwb2x5Z2xvdC10aWNrZXRpbmctdjEvcHJvdG9nZW4vZ28vdGlja2V0cy92MTt0aWNrZXRzdjFiBnByb3RvMw", [file_google_protobuf_timestamp, file_tickets_v1_tickets]);

/**
 * TicketCreated is an immutable snapshot of a ticket at creation time.
 *
 * @generated from message tickets.v1.TicketCreated
 */
export type TicketCreated = Message<"tickets.v1.TicketCreated"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;

  /**
   * @generated from field: google.protobuf.Timestamp occurred_at = 2;
   */
  occurredAt?: Timestamp | undefined;

  /**
   * @generated from field: tickets.v1.Ticket ticket = 3;
   */
  ticket?: Ticket | undefined;
};

/**
 * Describes the message tickets.v1.TicketCreated.
 * Use `create(TicketCreatedSchema)` to create a new message.
 */
export const TicketCreatedSchema: GenMessage<TicketCreated> = /*@__PURE__*/
  messageDesc(file_tickets_v1_events, 0);

/**
 * TicketUpdated is an immutable snapshot of a ticket after an update.
 *
 * @generated from message tickets.v1.TicketUpdated
 */
export type TicketUpdated = Message<"tickets.v1.TicketUpdated"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;

  /**
   * @generated from field: google.protobuf.Timestamp occurred_at = 2;
   */
  occurredAt?: Timestamp | undefined;

  /**
   * @generated from field: tickets.v1.Ticket ticket = 3;
   */
  ticket?: Ticket | undefined;
};

/**
 * Describes the message tickets.v1.TicketUpdated.
 * Use `create(TicketUpdatedSchema)` to create a new message.
 */
export const TicketUpdatedSchema: GenMessage<TicketUpdated> = /*@__PURE__*/
  messageDesc(file_tickets_v1_events, 1);

