// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file tickets/v1/tickets.proto (package tickets.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tickets/v1/tickets.proto.
 */
export const file_tickets_v1_tickets: GenFile = /*@__PURE__*/
  fileDesc("Chh0aWNrZXRzL3YxL3RpY2tldHMucHJvdG8SCnRpY2tldHMudjEiRAoTQ3JlYXRlVGlja2V0UmVxdWVzdBINCgV0aXRsZRgBIAEoCRINCgVwcmljZRgCIAEoAxIPCgd1c2VyX2lkGAMgASgJIlEKFENyZWF0ZVRpY2tldFJlc3BvbnNlEgoKAmlkGAEgASgJEg0KBXRpdGxlGAIgASgJEg0KBXByaWNlGAMgASgDEg8KB3VzZXJfaWQYBCABKAkyYwoOVGlja2V0c1NlcnZpY2USUQoMQ3JlYXRlVGlja2V0Eh8udGlja2V0cy52MS5DcmVhdGVUaWNrZXRSZXF1ZXN0GiAudGlja2V0cy52MS5DcmVhdGVUaWNrZXRSZXNwb25zZUI9Wjtwb2x5Z2xvdC10aWNrZXRpbmctdjEvYXBwcy90aWNrZXRzL2dlbi90aWNrZXRzL3YxO3RpY2tldHN2MWIGcHJvdG8z");

/**
 * @generated from message tickets.v1.CreateTicketRequest
 */
export type CreateTicketRequest = Message<"tickets.v1.CreateTicketRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: int64 price = 2;
   */
  price: bigint;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;
};

/**
 * Describes the message tickets.v1.CreateTicketRequest.
 * Use `create(CreateTicketRequestSchema)` to create a new message.
 */
export const CreateTicketRequestSchema: GenMessage<CreateTicketRequest> = /*@__PURE__*/
  messageDesc(file_tickets_v1_tickets, 0);

/**
 * @generated from message tickets.v1.CreateTicketResponse
 */
export type CreateTicketResponse = Message<"tickets.v1.CreateTicketResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: int64 price = 3;
   */
  price: bigint;

  /**
   * @generated from field: string user_id = 4;
   */
  userId: string;
};

/**
 * Describes the message tickets.v1.CreateTicketResponse.
 * Use `create(CreateTicketResponseSchema)` to create a new message.
 */
export const CreateTicketResponseSchema: GenMessage<CreateTicketResponse> = /*@__PURE__*/
  messageDesc(file_tickets_v1_tickets, 1);

/**
 * @generated from service tickets.v1.TicketsService
 */
export const TicketsService: GenService<{
  /**
   * @generated from rpc tickets.v1.TicketsService.CreateTicket
   */
  createTicket: {
    methodKind: "unary";
    input: typeof CreateTicketRequestSchema;
    output: typeof CreateTicketResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_tickets_v1_tickets, 0);

