// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file common/v1/error.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/error.proto.
 */
export const file_common_v1_error: GenFile = /*@__PURE__*/
  fileDesc("ChVjb21tb24vdjEvZXJyb3IucHJvdG8SCWNvbW1vbi52MSJECgVFcnJvchIPCgdtZXNzYWdlGAEgASgJEgwKBGNvZGUYAiABKAkSEgoFZmllbGQYAyABKAlIAIgBAUIICgZfZmllbGQiMQoNRXJyb3JSZXNwb25zZRIgCgZlcnJvcnMYASADKAsyEC5jb21tb24udjEuRXJyb3JCO1o5cG9seWdsb3QtdGlja2V0aW5nLXYxL2FwcHMvdGlja2V0cy9nZW4vY29tbW9uL3YxO2NvbW1vbnYxYgZwcm90bzM");

/**
 * A client-safe application error. Error codes are stable public API values.
 *
 * @generated from message common.v1.Error
 */
export type Error = Message<"common.v1.Error"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * @generated from field: optional string field = 3;
   */
  field?: string | undefined;
};

/**
 * Describes the message common.v1.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_common_v1_error, 0);

/**
 * @generated from message common.v1.ErrorResponse
 */
export type ErrorResponse = Message<"common.v1.ErrorResponse"> & {
  /**
   * @generated from field: repeated common.v1.Error errors = 1;
   */
  errors: Error[];
};

/**
 * Describes the message common.v1.ErrorResponse.
 * Use `create(ErrorResponseSchema)` to create a new message.
 */
export const ErrorResponseSchema: GenMessage<ErrorResponse> = /*@__PURE__*/
  messageDesc(file_common_v1_error, 1);

