services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile.dev
    image: api-gateway:dev
    container_name: api-gateway
    environment:
      NODE_ENV: development
      PORT: 3000
      IDENTITY_GRPC_URL: identity:50051
    ports:
      - "3000:3000"
    depends_on:
      - identity

  identity:
    build:
      context: .
      dockerfile: apps/identity/Dockerfile.dev
    image: identity:dev
    container_name: identity
    environment:
      NODE_ENV: development
      PORT: 3001
      GRPC_PORT: 50051
    ports:
      - "3001:3001"
    expose:
      - "50051"
