// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file identity/v1/identity.proto (package identity.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file identity/v1/identity.proto.
 */
export const file_identity_v1_identity: GenFile = /*@__PURE__*/
  fileDesc("ChppZGVudGl0eS92MS9pZGVudGl0eS5wcm90bxILaWRlbnRpdHkudjEiYgoNU2lnblVwUmVxdWVzdBIbCgRuYW1lGAEgASgJQg26SApyCDIGLipcUy4qEhYKBWVtYWlsGAIgASgJQge6SARyAmABEhwKCHBhc3N3b3JkGAMgASgJQgq6SAdyBRAIGIABIjAKDlNpZ25VcFJlc3BvbnNlEg8KB3VzZXJfaWQYASABKAkSDQoFZW1haWwYAiABKAkiRQoNU2lnbkluUmVxdWVzdBIWCgVlbWFpbBgBIAEoCUIHukgEcgJgARIcCghwYXNzd29yZBgCIAEoCUIKukgHcgUQCBiAASKlAQoOU2lnbkluUmVzcG9uc2USDwoHdXNlcl9pZBgBIAEoCRIMCgRuYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJEhYKDmVtYWlsX3ZlcmlmaWVkGAQgASgIEhUKDXNlc3Npb25fdG9rZW4YBSABKAkSNgoSc2Vzc2lvbl9leHBpcmVzX2F0GAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCIsChJWZXJpZnlFbWFpbFJlcXVlc3QSFgoFdG9rZW4YASABKAlCB7pIBHICEAEiJwoTVmVyaWZ5RW1haWxSZXNwb25zZRIQCgh2ZXJpZmllZBgBIAEoCDLpAQoPSWRlbnRpdHlTZXJ2aWNlEkEKBlNpZ25VcBIaLmlkZW50aXR5LnYxLlNpZ25VcFJlcXVlc3QaGy5pZGVudGl0eS52MS5TaWduVXBSZXNwb25zZRJBCgZTaWduSW4SGi5pZGVudGl0eS52MS5TaWduSW5SZXF1ZXN0GhsuaWRlbnRpdHkudjEuU2lnbkluUmVzcG9uc2USUAoLVmVyaWZ5RW1haWwSHy5pZGVudGl0eS52MS5WZXJpZnlFbWFpbFJlcXVlc3QaIC5pZGVudGl0eS52MS5WZXJpZnlFbWFpbFJlc3BvbnNlYgZwcm90bzM", [file_buf_validate_validate, file_google_protobuf_timestamp]);

/**
 * @generated from message identity.v1.SignUpRequest
 */
export type SignUpRequest = Message<"identity.v1.SignUpRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message identity.v1.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema: GenMessage<SignUpRequest> = /*@__PURE__*/
  messageDesc(file_identity_v1_identity, 0);

/**
 * @generated from message identity.v1.SignUpResponse
 */
export type SignUpResponse = Message<"identity.v1.SignUpResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;
};

/**
 * Describes the message identity.v1.SignUpResponse.
 * Use `create(SignUpResponseSchema)` to create a new message.
 */
export const SignUpResponseSchema: GenMessage<SignUpResponse> = /*@__PURE__*/
  messageDesc(file_identity_v1_identity, 1);

/**
 * @generated from message identity.v1.SignInRequest
 */
export type SignInRequest = Message<"identity.v1.SignInRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message identity.v1.SignInRequest.
 * Use `create(SignInRequestSchema)` to create a new message.
 */
export const SignInRequestSchema: GenMessage<SignInRequest> = /*@__PURE__*/
  messageDesc(file_identity_v1_identity, 2);

/**
 * @generated from message identity.v1.SignInResponse
 */
export type SignInResponse = Message<"identity.v1.SignInResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: bool email_verified = 4;
   */
  emailVerified: boolean;

  /**
   * @generated from field: string session_token = 5;
   */
  sessionToken: string;

  /**
   * @generated from field: google.protobuf.Timestamp session_expires_at = 6;
   */
  sessionExpiresAt?: Timestamp | undefined;
};

/**
 * Describes the message identity.v1.SignInResponse.
 * Use `create(SignInResponseSchema)` to create a new message.
 */
export const SignInResponseSchema: GenMessage<SignInResponse> = /*@__PURE__*/
  messageDesc(file_identity_v1_identity, 3);

/**
 * @generated from message identity.v1.VerifyEmailRequest
 */
export type VerifyEmailRequest = Message<"identity.v1.VerifyEmailRequest"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message identity.v1.VerifyEmailRequest.
 * Use `create(VerifyEmailRequestSchema)` to create a new message.
 */
export const VerifyEmailRequestSchema: GenMessage<VerifyEmailRequest> = /*@__PURE__*/
  messageDesc(file_identity_v1_identity, 4);

/**
 * @generated from message identity.v1.VerifyEmailResponse
 */
export type VerifyEmailResponse = Message<"identity.v1.VerifyEmailResponse"> & {
  /**
   * @generated from field: bool verified = 1;
   */
  verified: boolean;
};

/**
 * Describes the message identity.v1.VerifyEmailResponse.
 * Use `create(VerifyEmailResponseSchema)` to create a new message.
 */
export const VerifyEmailResponseSchema: GenMessage<VerifyEmailResponse> = /*@__PURE__*/
  messageDesc(file_identity_v1_identity, 5);

/**
 * @generated from service identity.v1.IdentityService
 */
export const IdentityService: GenService<{
  /**
   * @generated from rpc identity.v1.IdentityService.SignUp
   */
  signUp: {
    methodKind: "unary";
    input: typeof SignUpRequestSchema;
    output: typeof SignUpResponseSchema;
  },
  /**
   * @generated from rpc identity.v1.IdentityService.SignIn
   */
  signIn: {
    methodKind: "unary";
    input: typeof SignInRequestSchema;
    output: typeof SignInResponseSchema;
  },
  /**
   * @generated from rpc identity.v1.IdentityService.VerifyEmail
   */
  verifyEmail: {
    methodKind: "unary";
    input: typeof VerifyEmailRequestSchema;
    output: typeof VerifyEmailResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_identity_v1_identity, 0);

