// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file identity/v1/identity.proto (package identity.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file identity/v1/identity.proto.
 */
export const file_identity_v1_identity: GenFile = /*@__PURE__*/
  fileDesc("ChppZGVudGl0eS92MS9pZGVudGl0eS5wcm90bxILaWRlbnRpdHkudjEiYgoNU2lnblVwUmVxdWVzdBIbCgRuYW1lGAEgASgJQg26SApyCDIGLipcUy4qEhYKBWVtYWlsGAIgASgJQge6SARyAmABEhwKCHBhc3N3b3JkGAMgASgJQgq6SAdyBRAIGIABIjAKDlNpZ25VcFJlc3BvbnNlEg8KB3VzZXJfaWQYASABKAkSDQoFZW1haWwYAiABKAkyVAoPSWRlbnRpdHlTZXJ2aWNlEkEKBlNpZ25VcBIaLmlkZW50aXR5LnYxLlNpZ25VcFJlcXVlc3QaGy5pZGVudGl0eS52MS5TaWduVXBSZXNwb25zZWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * @generated from message identity.v1.SignUpRequest
 */
export type SignUpRequest = Message<"identity.v1.SignUpRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message identity.v1.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema: GenMessage<SignUpRequest> = /*@__PURE__*/
  messageDesc(file_identity_v1_identity, 0);

/**
 * @generated from message identity.v1.SignUpResponse
 */
export type SignUpResponse = Message<"identity.v1.SignUpResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;
};

/**
 * Describes the message identity.v1.SignUpResponse.
 * Use `create(SignUpResponseSchema)` to create a new message.
 */
export const SignUpResponseSchema: GenMessage<SignUpResponse> = /*@__PURE__*/
  messageDesc(file_identity_v1_identity, 1);

/**
 * @generated from service identity.v1.IdentityService
 */
export const IdentityService: GenService<{
  /**
   * @generated from rpc identity.v1.IdentityService.SignUp
   */
  signUp: {
    methodKind: "unary";
    input: typeof SignUpRequestSchema;
    output: typeof SignUpResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_identity_v1_identity, 0);

