// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file orders/v1/orders.proto (package orders.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file orders/v1/orders.proto.
 */
export const file_orders_v1_orders: GenFile = /*@__PURE__*/
  fileDesc("ChZvcmRlcnMvdjEvb3JkZXJzLnByb3RvEglvcmRlcnMudjEiOAoSQ3JlYXRlT3JkZXJSZXF1ZXN0EhEKCXRpY2tldF9pZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJIp0BChNDcmVhdGVPcmRlclJlc3BvbnNlEgoKAmlkGAEgASgJEi4KCmV4cGlyZXNfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg8KB3VzZXJfaWQYAyABKAkSEQoJdGlja2V0X2lkGAQgASgJEiYKBnN0YXR1cxgFIAEoDjIWLm9yZGVycy52MS5PcmRlclN0YXR1cyqeAQoLT3JkZXJTdGF0dXMSHAoYT1JERVJfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGAoUT1JERVJfU1RBVFVTX0NSRUFURUQQARIZChVPUkRFUl9TVEFUVVNfQ0FOQ0VMRUQQAhIhCh1PUkRFUl9TVEFUVVNfQVdBSVRJTkdfUEFZTUVOVBADEhkKFU9SREVSX1NUQVRVU19DT01QTEVURRAEMl0KDU9yZGVyc1NlcnZpY2USTAoLQ3JlYXRlT3JkZXISHS5vcmRlcnMudjEuQ3JlYXRlT3JkZXJSZXF1ZXN0Gh4ub3JkZXJzLnYxLkNyZWF0ZU9yZGVyUmVzcG9uc2VCNlo0cG9seWdsb3QtdGlja2V0aW5nLXYxL3Byb3RvZ2VuL2dvL29yZGVycy92MTtvcmRlcnN2MWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message orders.v1.CreateOrderRequest
 */
export type CreateOrderRequest = Message<"orders.v1.CreateOrderRequest"> & {
  /**
   * @generated from field: string ticket_id = 1;
   */
  ticketId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * Describes the message orders.v1.CreateOrderRequest.
 * Use `create(CreateOrderRequestSchema)` to create a new message.
 */
export const CreateOrderRequestSchema: GenMessage<CreateOrderRequest> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 0);

/**
 * @generated from message orders.v1.CreateOrderResponse
 */
export type CreateOrderResponse = Message<"orders.v1.CreateOrderResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 2;
   */
  expiresAt?: Timestamp | undefined;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: string ticket_id = 4;
   */
  ticketId: string;

  /**
   * @generated from field: orders.v1.OrderStatus status = 5;
   */
  status: OrderStatus;
};

/**
 * Describes the message orders.v1.CreateOrderResponse.
 * Use `create(CreateOrderResponseSchema)` to create a new message.
 */
export const CreateOrderResponseSchema: GenMessage<CreateOrderResponse> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 1);

/**
 * @generated from enum orders.v1.OrderStatus
 */
export enum OrderStatus {
  /**
   * @generated from enum value: ORDER_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ORDER_STATUS_CREATED = 1;
   */
  CREATED = 1,

  /**
   * @generated from enum value: ORDER_STATUS_CANCELED = 2;
   */
  CANCELED = 2,

  /**
   * @generated from enum value: ORDER_STATUS_AWAITING_PAYMENT = 3;
   */
  AWAITING_PAYMENT = 3,

  /**
   * @generated from enum value: ORDER_STATUS_COMPLETE = 4;
   */
  COMPLETE = 4,
}

/**
 * Describes the enum orders.v1.OrderStatus.
 */
export const OrderStatusSchema: GenEnum<OrderStatus> = /*@__PURE__*/
  enumDesc(file_orders_v1_orders, 0);

/**
 * @generated from service orders.v1.OrdersService
 */
export const OrdersService: GenService<{
  /**
   * @generated from rpc orders.v1.OrdersService.CreateOrder
   */
  createOrder: {
    methodKind: "unary";
    input: typeof CreateOrderRequestSchema;
    output: typeof CreateOrderResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_orders_v1_orders, 0);

