// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file orders/v1/orders.proto (package orders.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file orders/v1/orders.proto.
 */
export const file_orders_v1_orders: GenFile = /*@__PURE__*/
  fileDesc("ChZvcmRlcnMvdjEvb3JkZXJzLnByb3RvEglvcmRlcnMudjEiOAoSQ3JlYXRlT3JkZXJSZXF1ZXN0EhEKCXRpY2tldF9pZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJIq4BChNDcmVhdGVPcmRlclJlc3BvbnNlEgoKAmlkGAEgASgJEi4KCmV4cGlyZXNfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg8KB3VzZXJfaWQYAyABKAkSEQoJdGlja2V0X2lkGAQgASgJEiYKBnN0YXR1cxgFIAEoDjIWLm9yZGVycy52MS5PcmRlclN0YXR1cxIPCgdjcmVhdGVkGAYgASgIIjQKD0dldE9yZGVyUmVxdWVzdBIQCghvcmRlcl9pZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJIjMKEEdldE9yZGVyUmVzcG9uc2USHwoFb3JkZXIYASABKAsyEC5vcmRlcnMudjEuT3JkZXIiJAoRTGlzdE9yZGVyc1JlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCSI2ChJMaXN0T3JkZXJzUmVzcG9uc2USIAoGb3JkZXJzGAEgAygLMhAub3JkZXJzLnYxLk9yZGVyIo8BCgVPcmRlchIKCgJpZBgBIAEoCRIuCgpleHBpcmVzX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIPCgd1c2VyX2lkGAMgASgJEhEKCXRpY2tldF9pZBgEIAEoCRImCgZzdGF0dXMYBSABKA4yFi5vcmRlcnMudjEuT3JkZXJTdGF0dXMqngEKC09yZGVyU3RhdHVzEhwKGE9SREVSX1NUQVRVU19VTlNQRUNJRklFRBAAEhgKFE9SREVSX1NUQVRVU19DUkVBVEVEEAESGQoVT1JERVJfU1RBVFVTX0NBTkNFTEVEEAISIQodT1JERVJfU1RBVFVTX0FXQUlUSU5HX1BBWU1FTlQQAxIZChVPUkRFUl9TVEFUVVNfQ09NUExFVEUQBDLtAQoNT3JkZXJzU2VydmljZRJMCgtDcmVhdGVPcmRlchIdLm9yZGVycy52MS5DcmVhdGVPcmRlclJlcXVlc3QaHi5vcmRlcnMudjEuQ3JlYXRlT3JkZXJSZXNwb25zZRJDCghHZXRPcmRlchIaLm9yZGVycy52MS5HZXRPcmRlclJlcXVlc3QaGy5vcmRlcnMudjEuR2V0T3JkZXJSZXNwb25zZRJJCgpMaXN0T3JkZXJzEhwub3JkZXJzLnYxLkxpc3RPcmRlcnNSZXF1ZXN0Gh0ub3JkZXJzLnYxLkxpc3RPcmRlcnNSZXNwb25zZUI2WjRwb2x5Z2xvdC10aWNrZXRpbmctdjEvcHJvdG9nZW4vZ28vb3JkZXJzL3YxO29yZGVyc3YxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message orders.v1.CreateOrderRequest
 */
export type CreateOrderRequest = Message<"orders.v1.CreateOrderRequest"> & {
  /**
   * @generated from field: string ticket_id = 1;
   */
  ticketId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * Describes the message orders.v1.CreateOrderRequest.
 * Use `create(CreateOrderRequestSchema)` to create a new message.
 */
export const CreateOrderRequestSchema: GenMessage<CreateOrderRequest> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 0);

/**
 * @generated from message orders.v1.CreateOrderResponse
 */
export type CreateOrderResponse = Message<"orders.v1.CreateOrderResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 2;
   */
  expiresAt?: Timestamp | undefined;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: string ticket_id = 4;
   */
  ticketId: string;

  /**
   * @generated from field: orders.v1.OrderStatus status = 5;
   */
  status: OrderStatus;

  /**
   * @generated from field: bool created = 6;
   */
  created: boolean;
};

/**
 * Describes the message orders.v1.CreateOrderResponse.
 * Use `create(CreateOrderResponseSchema)` to create a new message.
 */
export const CreateOrderResponseSchema: GenMessage<CreateOrderResponse> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 1);

/**
 * @generated from message orders.v1.GetOrderRequest
 */
export type GetOrderRequest = Message<"orders.v1.GetOrderRequest"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * Describes the message orders.v1.GetOrderRequest.
 * Use `create(GetOrderRequestSchema)` to create a new message.
 */
export const GetOrderRequestSchema: GenMessage<GetOrderRequest> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 2);

/**
 * @generated from message orders.v1.GetOrderResponse
 */
export type GetOrderResponse = Message<"orders.v1.GetOrderResponse"> & {
  /**
   * @generated from field: orders.v1.Order order = 1;
   */
  order?: Order | undefined;
};

/**
 * Describes the message orders.v1.GetOrderResponse.
 * Use `create(GetOrderResponseSchema)` to create a new message.
 */
export const GetOrderResponseSchema: GenMessage<GetOrderResponse> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 3);

/**
 * @generated from message orders.v1.ListOrdersRequest
 */
export type ListOrdersRequest = Message<"orders.v1.ListOrdersRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message orders.v1.ListOrdersRequest.
 * Use `create(ListOrdersRequestSchema)` to create a new message.
 */
export const ListOrdersRequestSchema: GenMessage<ListOrdersRequest> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 4);

/**
 * @generated from message orders.v1.ListOrdersResponse
 */
export type ListOrdersResponse = Message<"orders.v1.ListOrdersResponse"> & {
  /**
   * @generated from field: repeated orders.v1.Order orders = 1;
   */
  orders: Order[];
};

/**
 * Describes the message orders.v1.ListOrdersResponse.
 * Use `create(ListOrdersResponseSchema)` to create a new message.
 */
export const ListOrdersResponseSchema: GenMessage<ListOrdersResponse> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 5);

/**
 * @generated from message orders.v1.Order
 */
export type Order = Message<"orders.v1.Order"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 2;
   */
  expiresAt?: Timestamp | undefined;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: string ticket_id = 4;
   */
  ticketId: string;

  /**
   * @generated from field: orders.v1.OrderStatus status = 5;
   */
  status: OrderStatus;
};

/**
 * Describes the message orders.v1.Order.
 * Use `create(OrderSchema)` to create a new message.
 */
export const OrderSchema: GenMessage<Order> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 6);

/**
 * @generated from enum orders.v1.OrderStatus
 */
export enum OrderStatus {
  /**
   * @generated from enum value: ORDER_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ORDER_STATUS_CREATED = 1;
   */
  CREATED = 1,

  /**
   * @generated from enum value: ORDER_STATUS_CANCELED = 2;
   */
  CANCELED = 2,

  /**
   * @generated from enum value: ORDER_STATUS_AWAITING_PAYMENT = 3;
   */
  AWAITING_PAYMENT = 3,

  /**
   * @generated from enum value: ORDER_STATUS_COMPLETE = 4;
   */
  COMPLETE = 4,
}

/**
 * Describes the enum orders.v1.OrderStatus.
 */
export const OrderStatusSchema: GenEnum<OrderStatus> = /*@__PURE__*/
  enumDesc(file_orders_v1_orders, 0);

/**
 * @generated from service orders.v1.OrdersService
 */
export const OrdersService: GenService<{
  /**
   * @generated from rpc orders.v1.OrdersService.CreateOrder
   */
  createOrder: {
    methodKind: "unary";
    input: typeof CreateOrderRequestSchema;
    output: typeof CreateOrderResponseSchema;
  },
  /**
   * @generated from rpc orders.v1.OrdersService.GetOrder
   */
  getOrder: {
    methodKind: "unary";
    input: typeof GetOrderRequestSchema;
    output: typeof GetOrderResponseSchema;
  },
  /**
   * @generated from rpc orders.v1.OrdersService.ListOrders
   */
  listOrders: {
    methodKind: "unary";
    input: typeof ListOrdersRequestSchema;
    output: typeof ListOrdersResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_orders_v1_orders, 0);

