// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file orders/v1/orders.proto (package orders.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file orders/v1/orders.proto.
 */
export const file_orders_v1_orders: GenFile = /*@__PURE__*/
  fileDesc("ChZvcmRlcnMvdjEvb3JkZXJzLnByb3RvEglvcmRlcnMudjEiOAoSQ3JlYXRlT3JkZXJSZXF1ZXN0EhEKCXRpY2tldF9pZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJIq4BChNDcmVhdGVPcmRlclJlc3BvbnNlEgoKAmlkGAEgASgJEi4KCmV4cGlyZXNfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg8KB3VzZXJfaWQYAyABKAkSEQoJdGlja2V0X2lkGAQgASgJEiYKBnN0YXR1cxgFIAEoDjIWLm9yZGVycy52MS5PcmRlclN0YXR1cxIPCgdjcmVhdGVkGAYgASgIIjcKEkNhbmNlbE9yZGVyUmVxdWVzdBIQCghvcmRlcl9pZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJIjYKE0NhbmNlbE9yZGVyUmVzcG9uc2USHwoFb3JkZXIYASABKAsyEC5vcmRlcnMudjEuT3JkZXIiNAoPR2V0T3JkZXJSZXF1ZXN0EhAKCG9yZGVyX2lkGAEgASgJEg8KB3VzZXJfaWQYAiABKAkiMwoQR2V0T3JkZXJSZXNwb25zZRIfCgVvcmRlchgBIAEoCzIQLm9yZGVycy52MS5PcmRlciIkChFMaXN0T3JkZXJzUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJIjYKEkxpc3RPcmRlcnNSZXNwb25zZRIgCgZvcmRlcnMYASADKAsyEC5vcmRlcnMudjEuT3JkZXIijwEKBU9yZGVyEgoKAmlkGAEgASgJEi4KCmV4cGlyZXNfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg8KB3VzZXJfaWQYAyABKAkSEQoJdGlja2V0X2lkGAQgASgJEiYKBnN0YXR1cxgFIAEoDjIWLm9yZGVycy52MS5PcmRlclN0YXR1cyqeAQoLT3JkZXJTdGF0dXMSHAoYT1JERVJfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGAoUT1JERVJfU1RBVFVTX0NSRUFURUQQARIZChVPUkRFUl9TVEFUVVNfQ0FOQ0VMRUQQAhIhCh1PUkRFUl9TVEFUVVNfQVdBSVRJTkdfUEFZTUVOVBADEhkKFU9SREVSX1NUQVRVU19DT01QTEVURRAEMrsCCg1PcmRlcnNTZXJ2aWNlEkwKC0NhbmNlbE9yZGVyEh0ub3JkZXJzLnYxLkNhbmNlbE9yZGVyUmVxdWVzdBoeLm9yZGVycy52MS5DYW5jZWxPcmRlclJlc3BvbnNlEkwKC0NyZWF0ZU9yZGVyEh0ub3JkZXJzLnYxLkNyZWF0ZU9yZGVyUmVxdWVzdBoeLm9yZGVycy52MS5DcmVhdGVPcmRlclJlc3BvbnNlEkMKCEdldE9yZGVyEhoub3JkZXJzLnYxLkdldE9yZGVyUmVxdWVzdBobLm9yZGVycy52MS5HZXRPcmRlclJlc3BvbnNlEkkKCkxpc3RPcmRlcnMSHC5vcmRlcnMudjEuTGlzdE9yZGVyc1JlcXVlc3QaHS5vcmRlcnMudjEuTGlzdE9yZGVyc1Jlc3BvbnNlQjZaNHBvbHlnbG90LXRpY2tldGluZy12MS9wcm90b2dlbi9nby9vcmRlcnMvdjE7b3JkZXJzdjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message orders.v1.CreateOrderRequest
 */
export type CreateOrderRequest = Message<"orders.v1.CreateOrderRequest"> & {
  /**
   * @generated from field: string ticket_id = 1;
   */
  ticketId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * Describes the message orders.v1.CreateOrderRequest.
 * Use `create(CreateOrderRequestSchema)` to create a new message.
 */
export const CreateOrderRequestSchema: GenMessage<CreateOrderRequest> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 0);

/**
 * @generated from message orders.v1.CreateOrderResponse
 */
export type CreateOrderResponse = Message<"orders.v1.CreateOrderResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 2;
   */
  expiresAt?: Timestamp | undefined;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: string ticket_id = 4;
   */
  ticketId: string;

  /**
   * @generated from field: orders.v1.OrderStatus status = 5;
   */
  status: OrderStatus;

  /**
   * @generated from field: bool created = 6;
   */
  created: boolean;
};

/**
 * Describes the message orders.v1.CreateOrderResponse.
 * Use `create(CreateOrderResponseSchema)` to create a new message.
 */
export const CreateOrderResponseSchema: GenMessage<CreateOrderResponse> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 1);

/**
 * @generated from message orders.v1.CancelOrderRequest
 */
export type CancelOrderRequest = Message<"orders.v1.CancelOrderRequest"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * Describes the message orders.v1.CancelOrderRequest.
 * Use `create(CancelOrderRequestSchema)` to create a new message.
 */
export const CancelOrderRequestSchema: GenMessage<CancelOrderRequest> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 2);

/**
 * @generated from message orders.v1.CancelOrderResponse
 */
export type CancelOrderResponse = Message<"orders.v1.CancelOrderResponse"> & {
  /**
   * @generated from field: orders.v1.Order order = 1;
   */
  order?: Order | undefined;
};

/**
 * Describes the message orders.v1.CancelOrderResponse.
 * Use `create(CancelOrderResponseSchema)` to create a new message.
 */
export const CancelOrderResponseSchema: GenMessage<CancelOrderResponse> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 3);

/**
 * @generated from message orders.v1.GetOrderRequest
 */
export type GetOrderRequest = Message<"orders.v1.GetOrderRequest"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * Describes the message orders.v1.GetOrderRequest.
 * Use `create(GetOrderRequestSchema)` to create a new message.
 */
export const GetOrderRequestSchema: GenMessage<GetOrderRequest> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 4);

/**
 * @generated from message orders.v1.GetOrderResponse
 */
export type GetOrderResponse = Message<"orders.v1.GetOrderResponse"> & {
  /**
   * @generated from field: orders.v1.Order order = 1;
   */
  order?: Order | undefined;
};

/**
 * Describes the message orders.v1.GetOrderResponse.
 * Use `create(GetOrderResponseSchema)` to create a new message.
 */
export const GetOrderResponseSchema: GenMessage<GetOrderResponse> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 5);

/**
 * @generated from message orders.v1.ListOrdersRequest
 */
export type ListOrdersRequest = Message<"orders.v1.ListOrdersRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message orders.v1.ListOrdersRequest.
 * Use `create(ListOrdersRequestSchema)` to create a new message.
 */
export const ListOrdersRequestSchema: GenMessage<ListOrdersRequest> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 6);

/**
 * @generated from message orders.v1.ListOrdersResponse
 */
export type ListOrdersResponse = Message<"orders.v1.ListOrdersResponse"> & {
  /**
   * @generated from field: repeated orders.v1.Order orders = 1;
   */
  orders: Order[];
};

/**
 * Describes the message orders.v1.ListOrdersResponse.
 * Use `create(ListOrdersResponseSchema)` to create a new message.
 */
export const ListOrdersResponseSchema: GenMessage<ListOrdersResponse> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 7);

/**
 * @generated from message orders.v1.Order
 */
export type Order = Message<"orders.v1.Order"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 2;
   */
  expiresAt?: Timestamp | undefined;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: string ticket_id = 4;
   */
  ticketId: string;

  /**
   * @generated from field: orders.v1.OrderStatus status = 5;
   */
  status: OrderStatus;
};

/**
 * Describes the message orders.v1.Order.
 * Use `create(OrderSchema)` to create a new message.
 */
export const OrderSchema: GenMessage<Order> = /*@__PURE__*/
  messageDesc(file_orders_v1_orders, 8);

/**
 * @generated from enum orders.v1.OrderStatus
 */
export enum OrderStatus {
  /**
   * @generated from enum value: ORDER_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ORDER_STATUS_CREATED = 1;
   */
  CREATED = 1,

  /**
   * @generated from enum value: ORDER_STATUS_CANCELED = 2;
   */
  CANCELED = 2,

  /**
   * @generated from enum value: ORDER_STATUS_AWAITING_PAYMENT = 3;
   */
  AWAITING_PAYMENT = 3,

  /**
   * @generated from enum value: ORDER_STATUS_COMPLETE = 4;
   */
  COMPLETE = 4,
}

/**
 * Describes the enum orders.v1.OrderStatus.
 */
export const OrderStatusSchema: GenEnum<OrderStatus> = /*@__PURE__*/
  enumDesc(file_orders_v1_orders, 0);

/**
 * @generated from service orders.v1.OrdersService
 */
export const OrdersService: GenService<{
  /**
   * @generated from rpc orders.v1.OrdersService.CancelOrder
   */
  cancelOrder: {
    methodKind: "unary";
    input: typeof CancelOrderRequestSchema;
    output: typeof CancelOrderResponseSchema;
  },
  /**
   * @generated from rpc orders.v1.OrdersService.CreateOrder
   */
  createOrder: {
    methodKind: "unary";
    input: typeof CreateOrderRequestSchema;
    output: typeof CreateOrderResponseSchema;
  },
  /**
   * @generated from rpc orders.v1.OrdersService.GetOrder
   */
  getOrder: {
    methodKind: "unary";
    input: typeof GetOrderRequestSchema;
    output: typeof GetOrderResponseSchema;
  },
  /**
   * @generated from rpc orders.v1.OrdersService.ListOrders
   */
  listOrders: {
    methodKind: "unary";
    input: typeof ListOrdersRequestSchema;
    output: typeof ListOrdersResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_orders_v1_orders, 0);

