// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file expiration/v1/events.proto (package expiration.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file expiration/v1/events.proto.
 */
export const file_expiration_v1_events: GenFile = /*@__PURE__*/
  fileDesc("ChpleHBpcmF0aW9uL3YxL2V2ZW50cy5wcm90bxINZXhwaXJhdGlvbi52MSJpChJFeHBpcmF0aW9uQ29tcGxldGUSEAoIZXZlbnRfaWQYASABKAkSLwoLb2NjdXJyZWRfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhAKCG9yZGVyX2lkGAMgASgJQj5aPHBvbHlnbG90LXRpY2tldGluZy12MS9wcm90b2dlbi9nby9leHBpcmF0aW9uL3YxO2V4cGlyYXRpb252MWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * ExpirationComplete records that an order's expiration deadline has elapsed.
 *
 * @generated from message expiration.v1.ExpirationComplete
 */
export type ExpirationComplete = Message<"expiration.v1.ExpirationComplete"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;

  /**
   * @generated from field: google.protobuf.Timestamp occurred_at = 2;
   */
  occurredAt?: Timestamp | undefined;

  /**
   * @generated from field: string order_id = 3;
   */
  orderId: string;
};

/**
 * Describes the message expiration.v1.ExpirationComplete.
 * Use `create(ExpirationCompleteSchema)` to create a new message.
 */
export const ExpirationCompleteSchema: GenMessage<ExpirationComplete> = /*@__PURE__*/
  messageDesc(file_expiration_v1_events, 0);

