// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file payments/v1/payments.proto (package payments.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file payments/v1/payments.proto.
 */
export const file_payments_v1_payments: GenFile = /*@__PURE__*/
  fileDesc("ChpwYXltZW50cy92MS9wYXltZW50cy5wcm90bxILcGF5bWVudHMudjEiOQoUQ3JlYXRlUGF5bWVudFJlcXVlc3QSEAoIb3JkZXJfaWQYASABKAkSDwoHdXNlcl9pZBgCIAEoCSJPChVDcmVhdGVQYXltZW50UmVzcG9uc2USJQoHcGF5bWVudBgBIAEoCzIULnBheW1lbnRzLnYxLlBheW1lbnQSDwoHY3JlYXRlZBgCIAEoCCInCgdQYXltZW50EgoKAmlkGAEgASgJEhAKCG9yZGVyX2lkGAIgASgJMmkKD1BheW1lbnRzU2VydmljZRJWCg1DcmVhdGVQYXltZW50EiEucGF5bWVudHMudjEuQ3JlYXRlUGF5bWVudFJlcXVlc3QaIi5wYXltZW50cy52MS5DcmVhdGVQYXltZW50UmVzcG9uc2VCOlo4cG9seWdsb3QtdGlja2V0aW5nLXYxL3Byb3RvZ2VuL2dvL3BheW1lbnRzL3YxO3BheW1lbnRzdjFiBnByb3RvMw");

/**
 * @generated from message payments.v1.CreatePaymentRequest
 */
export type CreatePaymentRequest = Message<"payments.v1.CreatePaymentRequest"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * Describes the message payments.v1.CreatePaymentRequest.
 * Use `create(CreatePaymentRequestSchema)` to create a new message.
 */
export const CreatePaymentRequestSchema: GenMessage<CreatePaymentRequest> = /*@__PURE__*/
  messageDesc(file_payments_v1_payments, 0);

/**
 * @generated from message payments.v1.CreatePaymentResponse
 */
export type CreatePaymentResponse = Message<"payments.v1.CreatePaymentResponse"> & {
  /**
   * @generated from field: payments.v1.Payment payment = 1;
   */
  payment?: Payment | undefined;

  /**
   * @generated from field: bool created = 2;
   */
  created: boolean;
};

/**
 * Describes the message payments.v1.CreatePaymentResponse.
 * Use `create(CreatePaymentResponseSchema)` to create a new message.
 */
export const CreatePaymentResponseSchema: GenMessage<CreatePaymentResponse> = /*@__PURE__*/
  messageDesc(file_payments_v1_payments, 1);

/**
 * @generated from message payments.v1.Payment
 */
export type Payment = Message<"payments.v1.Payment"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string order_id = 2;
   */
  orderId: string;
};

/**
 * Describes the message payments.v1.Payment.
 * Use `create(PaymentSchema)` to create a new message.
 */
export const PaymentSchema: GenMessage<Payment> = /*@__PURE__*/
  messageDesc(file_payments_v1_payments, 2);

/**
 * @generated from service payments.v1.PaymentsService
 */
export const PaymentsService: GenService<{
  /**
   * @generated from rpc payments.v1.PaymentsService.CreatePayment
   */
  createPayment: {
    methodKind: "unary";
    input: typeof CreatePaymentRequestSchema;
    output: typeof CreatePaymentResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_payments_v1_payments, 0);

