// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: orders/v1/events.proto

package ordersv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderCreated is an immutable snapshot of a newly created order reservation.
type OrderCreated struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	OrderId          string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus      OrderStatus            `protobuf:"varint,4,opt,name=order_status,json=orderStatus,proto3,enum=orders.v1.OrderStatus" json:"order_status,omitempty"`
	UserId           string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Ticket           *OrderTicket           `protobuf:"bytes,7,opt,name=ticket,proto3" json:"ticket,omitempty"`
	AggregateVersion int64                  `protobuf:"varint,8,opt,name=aggregate_version,json=aggregateVersion,proto3" json:"aggregate_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	mi := &file_orders_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_orders_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreated) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OrderCreated) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *OrderCreated) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreated) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderCreated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderCreated) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *OrderCreated) GetTicket() *OrderTicket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *OrderCreated) GetAggregateVersion() int64 {
	if x != nil {
		return x.AggregateVersion
	}
	return 0
}

type OrderTicket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTicket) Reset() {
	*x = OrderTicket{}
	mi := &file_orders_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTicket) ProtoMessage() {}

func (x *OrderTicket) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTicket.ProtoReflect.Descriptor instead.
func (*OrderTicket) Descriptor() ([]byte, []int) {
	return file_orders_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderTicket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderTicket) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// OrderCanceled records that an order reservation was canceled.
type OrderCanceled struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	OrderId          string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Ticket           *OrderCanceledTicket   `protobuf:"bytes,4,opt,name=ticket,proto3" json:"ticket,omitempty"`
	AggregateVersion int64                  `protobuf:"varint,5,opt,name=aggregate_version,json=aggregateVersion,proto3" json:"aggregate_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderCanceled) Reset() {
	*x = OrderCanceled{}
	mi := &file_orders_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCanceled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCanceled) ProtoMessage() {}

func (x *OrderCanceled) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCanceled.ProtoReflect.Descriptor instead.
func (*OrderCanceled) Descriptor() ([]byte, []int) {
	return file_orders_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCanceled) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OrderCanceled) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *OrderCanceled) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCanceled) GetTicket() *OrderCanceledTicket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *OrderCanceled) GetAggregateVersion() int64 {
	if x != nil {
		return x.AggregateVersion
	}
	return 0
}

type OrderCanceledTicket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCanceledTicket) Reset() {
	*x = OrderCanceledTicket{}
	mi := &file_orders_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCanceledTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCanceledTicket) ProtoMessage() {}

func (x *OrderCanceledTicket) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCanceledTicket.ProtoReflect.Descriptor instead.
func (*OrderCanceledTicket) Descriptor() ([]byte, []int) {
	return file_orders_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *OrderCanceledTicket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_orders_v1_events_proto protoreflect.FileDescriptor

const file_orders_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x16orders/v1/events.proto\x12\torders.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16orders/v1/orders.proto\"\xed\x02\n" +
	"\fOrderCreated\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x129\n" +
	"\forder_status\x18\x04 \x01(\x0e2\x16.orders.v1.OrderStatusR\vorderStatus\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12.\n" +
	"\x06ticket\x18\a \x01(\v2\x16.orders.v1.OrderTicketR\x06ticket\x12+\n" +
	"\x11aggregate_version\x18\b \x01(\x03R\x10aggregateVersion\"3\n" +
	"\vOrderTicket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\"\xe7\x01\n" +
	"\rOrderCanceled\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x126\n" +
	"\x06ticket\x18\x04 \x01(\v2\x1e.orders.v1.OrderCanceledTicketR\x06ticket\x12+\n" +
	"\x11aggregate_version\x18\x05 \x01(\x03R\x10aggregateVersion\"%\n" +
	"\x13OrderCanceledTicket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB6Z4polyglot-ticketing-v1/protogen/go/orders/v1;ordersv1b\x06proto3"

var (
	file_orders_v1_events_proto_rawDescOnce sync.Once
	file_orders_v1_events_proto_rawDescData []byte
)

func file_orders_v1_events_proto_rawDescGZIP() []byte {
	file_orders_v1_events_proto_rawDescOnce.Do(func() {
		file_orders_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_v1_events_proto_rawDesc), len(file_orders_v1_events_proto_rawDesc)))
	})
	return file_orders_v1_events_proto_rawDescData
}

var file_orders_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orders_v1_events_proto_goTypes = []any{
	(*OrderCreated)(nil),          // 0: orders.v1.OrderCreated
	(*OrderTicket)(nil),           // 1: orders.v1.OrderTicket
	(*OrderCanceled)(nil),         // 2: orders.v1.OrderCanceled
	(*OrderCanceledTicket)(nil),   // 3: orders.v1.OrderCanceledTicket
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(OrderStatus)(0),              // 5: orders.v1.OrderStatus
}
var file_orders_v1_events_proto_depIdxs = []int32{
	4, // 0: orders.v1.OrderCreated.occurred_at:type_name -> google.protobuf.Timestamp
	5, // 1: orders.v1.OrderCreated.order_status:type_name -> orders.v1.OrderStatus
	4, // 2: orders.v1.OrderCreated.expires_at:type_name -> google.protobuf.Timestamp
	1, // 3: orders.v1.OrderCreated.ticket:type_name -> orders.v1.OrderTicket
	4, // 4: orders.v1.OrderCanceled.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 5: orders.v1.OrderCanceled.ticket:type_name -> orders.v1.OrderCanceledTicket
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_orders_v1_events_proto_init() }
func file_orders_v1_events_proto_init() {
	if File_orders_v1_events_proto != nil {
		return
	}
	file_orders_v1_orders_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_v1_events_proto_rawDesc), len(file_orders_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orders_v1_events_proto_goTypes,
		DependencyIndexes: file_orders_v1_events_proto_depIdxs,
		MessageInfos:      file_orders_v1_events_proto_msgTypes,
	}.Build()
	File_orders_v1_events_proto = out.File
	file_orders_v1_events_proto_goTypes = nil
	file_orders_v1_events_proto_depIdxs = nil
}
