// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: orders/v1/events.proto

package ordersv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderCreated is an immutable snapshot of a newly created order reservation.
type OrderCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus   OrderStatus            `protobuf:"varint,4,opt,name=order_status,json=orderStatus,proto3,enum=orders.v1.OrderStatus" json:"order_status,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Ticket        *OrderTicket           `protobuf:"bytes,7,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	mi := &file_orders_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_orders_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreated) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OrderCreated) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *OrderCreated) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreated) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderCreated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderCreated) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *OrderCreated) GetTicket() *OrderTicket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type OrderTicket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTicket) Reset() {
	*x = OrderTicket{}
	mi := &file_orders_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTicket) ProtoMessage() {}

func (x *OrderTicket) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTicket.ProtoReflect.Descriptor instead.
func (*OrderTicket) Descriptor() ([]byte, []int) {
	return file_orders_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderTicket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderTicket) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_orders_v1_events_proto protoreflect.FileDescriptor

const file_orders_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x16orders/v1/events.proto\x12\torders.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16orders/v1/orders.proto\"\xc0\x02\n" +
	"\fOrderCreated\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x129\n" +
	"\forder_status\x18\x04 \x01(\x0e2\x16.orders.v1.OrderStatusR\vorderStatus\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12.\n" +
	"\x06ticket\x18\a \x01(\v2\x16.orders.v1.OrderTicketR\x06ticket\"3\n" +
	"\vOrderTicket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05priceB6Z4polyglot-ticketing-v1/protogen/go/orders/v1;ordersv1b\x06proto3"

var (
	file_orders_v1_events_proto_rawDescOnce sync.Once
	file_orders_v1_events_proto_rawDescData []byte
)

func file_orders_v1_events_proto_rawDescGZIP() []byte {
	file_orders_v1_events_proto_rawDescOnce.Do(func() {
		file_orders_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_v1_events_proto_rawDesc), len(file_orders_v1_events_proto_rawDesc)))
	})
	return file_orders_v1_events_proto_rawDescData
}

var file_orders_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orders_v1_events_proto_goTypes = []any{
	(*OrderCreated)(nil),          // 0: orders.v1.OrderCreated
	(*OrderTicket)(nil),           // 1: orders.v1.OrderTicket
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(OrderStatus)(0),              // 3: orders.v1.OrderStatus
}
var file_orders_v1_events_proto_depIdxs = []int32{
	2, // 0: orders.v1.OrderCreated.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 1: orders.v1.OrderCreated.order_status:type_name -> orders.v1.OrderStatus
	2, // 2: orders.v1.OrderCreated.expires_at:type_name -> google.protobuf.Timestamp
	1, // 3: orders.v1.OrderCreated.ticket:type_name -> orders.v1.OrderTicket
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_orders_v1_events_proto_init() }
func file_orders_v1_events_proto_init() {
	if File_orders_v1_events_proto != nil {
		return
	}
	file_orders_v1_orders_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_v1_events_proto_rawDesc), len(file_orders_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orders_v1_events_proto_goTypes,
		DependencyIndexes: file_orders_v1_events_proto_depIdxs,
		MessageInfos:      file_orders_v1_events_proto_msgTypes,
	}.Build()
	File_orders_v1_events_proto = out.File
	file_orders_v1_events_proto_goTypes = nil
	file_orders_v1_events_proto_depIdxs = nil
}
