// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: expiration/v1/events.proto

package expirationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExpirationComplete records that an order's expiration deadline has elapsed.
type ExpirationComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpirationComplete) Reset() {
	*x = ExpirationComplete{}
	mi := &file_expiration_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpirationComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpirationComplete) ProtoMessage() {}

func (x *ExpirationComplete) ProtoReflect() protoreflect.Message {
	mi := &file_expiration_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpirationComplete.ProtoReflect.Descriptor instead.
func (*ExpirationComplete) Descriptor() ([]byte, []int) {
	return file_expiration_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *ExpirationComplete) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ExpirationComplete) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *ExpirationComplete) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_expiration_v1_events_proto protoreflect.FileDescriptor

const file_expiration_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1aexpiration/v1/events.proto\x12\rexpiration.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\x12ExpirationComplete\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderIdB>Z<polyglot-ticketing-v1/protogen/go/expiration/v1;expirationv1b\x06proto3"

var (
	file_expiration_v1_events_proto_rawDescOnce sync.Once
	file_expiration_v1_events_proto_rawDescData []byte
)

func file_expiration_v1_events_proto_rawDescGZIP() []byte {
	file_expiration_v1_events_proto_rawDescOnce.Do(func() {
		file_expiration_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expiration_v1_events_proto_rawDesc), len(file_expiration_v1_events_proto_rawDesc)))
	})
	return file_expiration_v1_events_proto_rawDescData
}

var file_expiration_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_expiration_v1_events_proto_goTypes = []any{
	(*ExpirationComplete)(nil),    // 0: expiration.v1.ExpirationComplete
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_expiration_v1_events_proto_depIdxs = []int32{
	1, // 0: expiration.v1.ExpirationComplete.occurred_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_expiration_v1_events_proto_init() }
func file_expiration_v1_events_proto_init() {
	if File_expiration_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expiration_v1_events_proto_rawDesc), len(file_expiration_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expiration_v1_events_proto_goTypes,
		DependencyIndexes: file_expiration_v1_events_proto_depIdxs,
		MessageInfos:      file_expiration_v1_events_proto_msgTypes,
	}.Build()
	File_expiration_v1_events_proto = out.File
	file_expiration_v1_events_proto_goTypes = nil
	file_expiration_v1_events_proto_depIdxs = nil
}
