// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tickets/v1/events.proto

package ticketsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TicketCreated is an immutable snapshot of a ticket at creation time.
type TicketCreated struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Ticket           *Ticket                `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	AggregateVersion int64                  `protobuf:"varint,4,opt,name=aggregate_version,json=aggregateVersion,proto3" json:"aggregate_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TicketCreated) Reset() {
	*x = TicketCreated{}
	mi := &file_tickets_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCreated) ProtoMessage() {}

func (x *TicketCreated) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCreated.ProtoReflect.Descriptor instead.
func (*TicketCreated) Descriptor() ([]byte, []int) {
	return file_tickets_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *TicketCreated) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TicketCreated) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TicketCreated) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *TicketCreated) GetAggregateVersion() int64 {
	if x != nil {
		return x.AggregateVersion
	}
	return 0
}

// TicketUpdated is an immutable snapshot of a ticket after an update.
type TicketUpdated struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Ticket           *Ticket                `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	AggregateVersion int64                  `protobuf:"varint,4,opt,name=aggregate_version,json=aggregateVersion,proto3" json:"aggregate_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TicketUpdated) Reset() {
	*x = TicketUpdated{}
	mi := &file_tickets_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketUpdated) ProtoMessage() {}

func (x *TicketUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketUpdated.ProtoReflect.Descriptor instead.
func (*TicketUpdated) Descriptor() ([]byte, []int) {
	return file_tickets_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *TicketUpdated) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TicketUpdated) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TicketUpdated) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *TicketUpdated) GetAggregateVersion() int64 {
	if x != nil {
		return x.AggregateVersion
	}
	return 0
}

var File_tickets_v1_events_proto protoreflect.FileDescriptor

const file_tickets_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x17tickets/v1/events.proto\x12\n" +
	"tickets.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18tickets/v1/tickets.proto\"\xc0\x01\n" +
	"\rTicketCreated\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12*\n" +
	"\x06ticket\x18\x03 \x01(\v2\x12.tickets.v1.TicketR\x06ticket\x12+\n" +
	"\x11aggregate_version\x18\x04 \x01(\x03R\x10aggregateVersion\"\xc0\x01\n" +
	"\rTicketUpdated\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12*\n" +
	"\x06ticket\x18\x03 \x01(\v2\x12.tickets.v1.TicketR\x06ticket\x12+\n" +
	"\x11aggregate_version\x18\x04 \x01(\x03R\x10aggregateVersionB8Z6polyglot-ticketing-v1/protogen/go/tickets/v1;ticketsv1b\x06proto3"

var (
	file_tickets_v1_events_proto_rawDescOnce sync.Once
	file_tickets_v1_events_proto_rawDescData []byte
)

func file_tickets_v1_events_proto_rawDescGZIP() []byte {
	file_tickets_v1_events_proto_rawDescOnce.Do(func() {
		file_tickets_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tickets_v1_events_proto_rawDesc), len(file_tickets_v1_events_proto_rawDesc)))
	})
	return file_tickets_v1_events_proto_rawDescData
}

var file_tickets_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tickets_v1_events_proto_goTypes = []any{
	(*TicketCreated)(nil),         // 0: tickets.v1.TicketCreated
	(*TicketUpdated)(nil),         // 1: tickets.v1.TicketUpdated
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*Ticket)(nil),                // 3: tickets.v1.Ticket
}
var file_tickets_v1_events_proto_depIdxs = []int32{
	2, // 0: tickets.v1.TicketCreated.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 1: tickets.v1.TicketCreated.ticket:type_name -> tickets.v1.Ticket
	2, // 2: tickets.v1.TicketUpdated.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 3: tickets.v1.TicketUpdated.ticket:type_name -> tickets.v1.Ticket
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tickets_v1_events_proto_init() }
func file_tickets_v1_events_proto_init() {
	if File_tickets_v1_events_proto != nil {
		return
	}
	file_tickets_v1_tickets_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tickets_v1_events_proto_rawDesc), len(file_tickets_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tickets_v1_events_proto_goTypes,
		DependencyIndexes: file_tickets_v1_events_proto_depIdxs,
		MessageInfos:      file_tickets_v1_events_proto_msgTypes,
	}.Build()
	File_tickets_v1_events_proto = out.File
	file_tickets_v1_events_proto_goTypes = nil
	file_tickets_v1_events_proto_depIdxs = nil
}
