// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tickets/v1/tickets.proto

package ticketsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketRequest) Reset() {
	*x = CreateTicketRequest{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRequest) ProtoMessage() {}

func (x *CreateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketRequest) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTicketRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTicketRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTicketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketResponse) Reset() {
	*x = CreateTicketResponse{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketResponse) ProtoMessage() {}

func (x *CreateTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketResponse.ProtoReflect.Descriptor instead.
func (*CreateTicketResponse) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTicketResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTicketResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTicketResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTicketResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketRequest) Reset() {
	*x = UpdateTicketRequest{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketRequest) ProtoMessage() {}

func (x *UpdateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketRequest) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTicketRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTicketRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTicketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketResponse) Reset() {
	*x = UpdateTicketResponse{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketResponse) ProtoMessage() {}

func (x *UpdateTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketResponse.ProtoReflect.Descriptor instead.
func (*UpdateTicketResponse) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{4}
}

func (x *GetTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketResponse) Reset() {
	*x = GetTicketResponse{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketResponse) ProtoMessage() {}

func (x *GetTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketResponse.ProtoReflect.Descriptor instead.
func (*GetTicketResponse) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{5}
}

func (x *GetTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type ListTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsRequest) Reset() {
	*x = ListTicketsRequest{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRequest) ProtoMessage() {}

func (x *ListTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRequest.ProtoReflect.Descriptor instead.
func (*ListTicketsRequest) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{6}
}

type ListTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsResponse) Reset() {
	*x = ListTicketsResponse{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResponse) ProtoMessage() {}

func (x *ListTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListTicketsResponse) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{7}
}

func (x *ListTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{8}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ticket) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Ticket) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_tickets_v1_tickets_proto protoreflect.FileDescriptor

const file_tickets_v1_tickets_proto_rawDesc = "" +
	"\n" +
	"\x18tickets/v1/tickets.proto\x12\n" +
	"tickets.v1\"Z\n" +
	"\x13CreateTicketRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"k\n" +
	"\x14CreateTicketResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"j\n" +
	"\x13UpdateTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"B\n" +
	"\x14UpdateTicketResponse\x12*\n" +
	"\x06ticket\x18\x01 \x01(\v2\x12.tickets.v1.TicketR\x06ticket\"\"\n" +
	"\x10GetTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x11GetTicketResponse\x12*\n" +
	"\x06ticket\x18\x01 \x01(\v2\x12.tickets.v1.TicketR\x06ticket\"\x14\n" +
	"\x12ListTicketsRequest\"C\n" +
	"\x13ListTicketsResponse\x12,\n" +
	"\atickets\x18\x01 \x03(\v2\x12.tickets.v1.TicketR\atickets\"]\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId2\xd0\x02\n" +
	"\x0eTicketsService\x12Q\n" +
	"\fCreateTicket\x12\x1f.tickets.v1.CreateTicketRequest\x1a .tickets.v1.CreateTicketResponse\x12Q\n" +
	"\fUpdateTicket\x12\x1f.tickets.v1.UpdateTicketRequest\x1a .tickets.v1.UpdateTicketResponse\x12H\n" +
	"\tGetTicket\x12\x1c.tickets.v1.GetTicketRequest\x1a\x1d.tickets.v1.GetTicketResponse\x12N\n" +
	"\vListTickets\x12\x1e.tickets.v1.ListTicketsRequest\x1a\x1f.tickets.v1.ListTicketsResponseB8Z6polyglot-ticketing-v1/protogen/go/tickets/v1;ticketsv1b\x06proto3"

var (
	file_tickets_v1_tickets_proto_rawDescOnce sync.Once
	file_tickets_v1_tickets_proto_rawDescData []byte
)

func file_tickets_v1_tickets_proto_rawDescGZIP() []byte {
	file_tickets_v1_tickets_proto_rawDescOnce.Do(func() {
		file_tickets_v1_tickets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tickets_v1_tickets_proto_rawDesc), len(file_tickets_v1_tickets_proto_rawDesc)))
	})
	return file_tickets_v1_tickets_proto_rawDescData
}

var file_tickets_v1_tickets_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tickets_v1_tickets_proto_goTypes = []any{
	(*CreateTicketRequest)(nil),  // 0: tickets.v1.CreateTicketRequest
	(*CreateTicketResponse)(nil), // 1: tickets.v1.CreateTicketResponse
	(*UpdateTicketRequest)(nil),  // 2: tickets.v1.UpdateTicketRequest
	(*UpdateTicketResponse)(nil), // 3: tickets.v1.UpdateTicketResponse
	(*GetTicketRequest)(nil),     // 4: tickets.v1.GetTicketRequest
	(*GetTicketResponse)(nil),    // 5: tickets.v1.GetTicketResponse
	(*ListTicketsRequest)(nil),   // 6: tickets.v1.ListTicketsRequest
	(*ListTicketsResponse)(nil),  // 7: tickets.v1.ListTicketsResponse
	(*Ticket)(nil),               // 8: tickets.v1.Ticket
}
var file_tickets_v1_tickets_proto_depIdxs = []int32{
	8, // 0: tickets.v1.UpdateTicketResponse.ticket:type_name -> tickets.v1.Ticket
	8, // 1: tickets.v1.GetTicketResponse.ticket:type_name -> tickets.v1.Ticket
	8, // 2: tickets.v1.ListTicketsResponse.tickets:type_name -> tickets.v1.Ticket
	0, // 3: tickets.v1.TicketsService.CreateTicket:input_type -> tickets.v1.CreateTicketRequest
	2, // 4: tickets.v1.TicketsService.UpdateTicket:input_type -> tickets.v1.UpdateTicketRequest
	4, // 5: tickets.v1.TicketsService.GetTicket:input_type -> tickets.v1.GetTicketRequest
	6, // 6: tickets.v1.TicketsService.ListTickets:input_type -> tickets.v1.ListTicketsRequest
	1, // 7: tickets.v1.TicketsService.CreateTicket:output_type -> tickets.v1.CreateTicketResponse
	3, // 8: tickets.v1.TicketsService.UpdateTicket:output_type -> tickets.v1.UpdateTicketResponse
	5, // 9: tickets.v1.TicketsService.GetTicket:output_type -> tickets.v1.GetTicketResponse
	7, // 10: tickets.v1.TicketsService.ListTickets:output_type -> tickets.v1.ListTicketsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tickets_v1_tickets_proto_init() }
func file_tickets_v1_tickets_proto_init() {
	if File_tickets_v1_tickets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tickets_v1_tickets_proto_rawDesc), len(file_tickets_v1_tickets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tickets_v1_tickets_proto_goTypes,
		DependencyIndexes: file_tickets_v1_tickets_proto_depIdxs,
		MessageInfos:      file_tickets_v1_tickets_proto_msgTypes,
	}.Build()
	File_tickets_v1_tickets_proto = out.File
	file_tickets_v1_tickets_proto_goTypes = nil
	file_tickets_v1_tickets_proto_depIdxs = nil
}
